-- ponytail: seed data for MVP, add more leaders as needed
INSERT INTO presidents (id, name, country, region, avatar_url, active) VALUES
('pres_001', 'Abdel Fattah el-Sisi', 'Egypt', 'Africa', '/avatars/abdel-fattah-el-sisi.png', 1),
('pres_002', 'Anthony Albanese', 'Australia', 'Oceania', '/avatars/anthony-albanese.png', 1),
('pres_003', 'Bola Tinubu', 'Nigeria', 'Africa', '/avatars/bola-tinubu.png', 1),
('pres_004', 'Claudia Sheinbaum', 'Mexico', 'Americas', '/avatars/claudia-sheinbaum.png', 1),
('pres_005', 'Cyril Ramaphosa', 'South Africa', 'Africa', '/avatars/cyril-ramaphosa.png', 1),
('pres_006', 'Dick Schoof', 'Netherlands', 'Europe', '/avatars/dick-schoof.png', 1),
('pres_007', 'Donald Trump', 'United States', 'Americas', '/avatars/donald-trump.png', 1),
('pres_008', 'Donald Tusk', 'Poland', 'Europe', '/avatars/donald-tusk.png', 1),
('pres_009', 'Emmanuel Macron', 'France', 'Europe', '/avatars/emmanuel-macron.png', 1),
('pres_010', 'Emmerson Mnangagwa', 'Zimbabwe', 'Africa', '/avatars/emmerson-mnangagwa.png', 1),
('pres_011', 'Friedrich Merz', 'Germany', 'Europe', '/avatars/friedrich-merz.png', 1),
('pres_012', 'Giorgia Meloni', 'Italy', 'Europe', '/avatars/giorgia-meloni.png', 1),
('pres_013', 'Javier Milei', 'Argentina', 'Americas', '/avatars/javier-milei.png', 1),
('pres_014', 'Jonas Gahr Støre', 'Norway', 'Europe', '/avatars/jonas-gahr-store.png', 1),
('pres_015', 'Keir Starmer', 'United Kingdom', 'Europe', '/avatars/keir-starmer.png', 1),
('pres_016', 'Lee Jae-myung', 'South Korea', 'Asia', '/avatars/lee-jae-myung.png', 1),
('pres_017', 'Lula da Silva', 'Brazil', 'Americas', '/avatars/lula-da-silva.png', 1),
('pres_018', 'Mark Carney', 'Canada', 'Americas', '/avatars/mark-carney.png', 1),
('pres_019', 'Narendra Modi', 'India', 'Asia', '/avatars/narendra-modi.png', 1),
('pres_020', 'Pedro Sánchez', 'Spain', 'Europe', '/avatars/pedro-sanchez.png', 1),
('pres_021', 'Recep Tayyip Erdoğan', 'Turkey', 'Asia', '/avatars/recep-tayyip-erdogan.png', 1),
('pres_022', 'Shigeru Ishiba', 'Japan', 'Asia', '/avatars/shigeru-ishiba.png', 1),
('pres_023', 'Ulf Kristersson', 'Sweden', 'Europe', '/avatars/ulf-kristersson.png', 1),
('pres_024', 'Vladimir Putin', 'Russia', 'Europe', '/avatars/vladimir-putin.png', 1),
('pres_025', 'Volodymyr Zelensky', 'Ukraine', 'Europe', '/avatars/volodymyr-zelensky.png', 1),
('pres_026', 'Xi Jinping', 'China', 'Asia', '/avatars/xi-jinping.png', 1);
